<a href="https://colab.research.google.com/github/teelch0/Data-Mining/blob/main/simple_attention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import tiktoken

In [ ]:
raw_text = "This is my dog Hazel"

In [ ]:
tokenizer = tiktoken.get_encoding("gpt2")

In [ ]:
enc_text = tokenizer.encode( raw_text )
print(enc_text)

[1212, 318, 616, 3290, 42805]


In [ ]:
vocab_size = 4
output_dim = 8
inputs = torch.nn.Embedding( vocab_size, output_dim )
print( inputs.weight )

Parameter containing:
tensor([[ 6.3263e-01,  5.5277e-01, -9.8654e-01,  1.9623e+00,  1.7586e-01,
         -3.2208e-01, -7.5031e-01, -1.5885e-02],
        [-6.7296e-01, -1.9618e+00,  1.1899e-01,  7.0622e-04,  1.8619e+00,
          1.5509e+00, -1.5443e+00,  5.6568e-01],
        [ 1.9351e-01,  7.9869e-01,  1.3246e+00, -8.8030e-01, -2.4391e-01,
          5.3702e-01,  7.9829e-01,  7.0993e-01],
        [ 4.8424e-01, -5.5483e-01, -5.0217e-01,  6.8145e-01,  4.2363e-01,
         -1.4344e-01,  9.2017e-01, -1.5657e+00]], requires_grad=True)


In [ ]:
inputs = inputs.weight.data
inputs

tensor([[ 6.3263e-01,  5.5277e-01, -9.8654e-01,  1.9623e+00,  1.7586e-01,
         -3.2208e-01, -7.5031e-01, -1.5885e-02],
        [-6.7296e-01, -1.9618e+00,  1.1899e-01,  7.0622e-04,  1.8619e+00,
          1.5509e+00, -1.5443e+00,  5.6568e-01],
        [ 1.9351e-01,  7.9869e-01,  1.3246e+00, -8.8030e-01, -2.4391e-01,
          5.3702e-01,  7.9829e-01,  7.0993e-01],
        [ 4.8424e-01, -5.5483e-01, -5.0217e-01,  6.8145e-01,  4.2363e-01,
         -1.4344e-01,  9.2017e-01, -1.5657e+00]])

In [ ]:
inputs.shape

torch.Size([4, 8])

In [ ]:
for row in inputs:
    print(row.tolist())

[0.6326289176940918, 0.5527703762054443, -0.9865354299545288, 1.9622715711593628, 0.17585885524749756, -0.3220824897289276, -0.7503109574317932, -0.01588471606373787]
[-0.6729590892791748, -1.9617974758148193, 0.1189877986907959, 0.0007062240620143712, 1.8618825674057007, 1.5508555173873901, -1.5442900657653809, 0.5656778812408447]
[0.19350700080394745, 0.7986892461776733, 1.3245874643325806, -0.8802977800369263, -0.24391230940818787, 0.537015438079834, 0.7982850670814514, 0.7099307775497437]
[0.48424404859542847, -0.5548260807991028, -0.5021741986274719, 0.6814503073692322, 0.4236266613006592, -0.14343969523906708, 0.9201672077178955, -1.565696120262146]


In [ ]:
x = torch.Tensor([1.1, 2.3])
y = torch.Tensor([3.4,-2.1])


In [ ]:
1.1*3.4 + 2.3*(-2.1)

-1.0899999999999999

In [ ]:
torch.dot( x, y)

tensor(-1.0900)

In [ ]:
query = inputs[2]
print(query)

tensor([ 0.1935,  0.7987,  1.3246, -0.8803, -0.2439,  0.5370,  0.7983,  0.7099])


In [ ]:
for i in range( len( inputs )):
    print( torch.dot( query, inputs[i] ) )

tensor(-3.2963)
tensor(-1.9926)
tensor(4.6939)
tensor(-2.1718)


In [ ]:
attention_scores_2 = torch.zeros( len(inputs) )
for i in range( len( inputs )):
    attention_scores_2[i] = torch.dot( query, inputs[i] )
print( attention_scores_2)

tensor([-3.2963, -1.9926,  4.6939, -2.1718])


In [ ]:
# normalize the attention scores using the softmax function:
# def softmax(x):
#     torch.exp(x) / torch.exp(x).sum()

In [ ]:
attention_weights_2 = torch.softmax( attention_scores_2, dim = 0 )
attention_weights_2

tensor([3.3786e-04, 1.2443e-03, 9.9738e-01, 1.0402e-03])

In [ ]:
attention_weights_2.sum()

tensor(1.)

In [ ]:
context_vector_2 = torch.zeros( query.shape )
for i in range( len( attention_weights_2 ) ):
    context_vector_2 += attention_weights_2[i]*inputs[i]
context_vector_2

tensor([ 0.1929,  0.7938,  1.3204, -0.8766, -0.2405,  0.5373,  0.7950,  0.7071])

In [ ]:
inputs

tensor([[ 6.3263e-01,  5.5277e-01, -9.8654e-01,  1.9623e+00,  1.7586e-01,
         -3.2208e-01, -7.5031e-01, -1.5885e-02],
        [-6.7296e-01, -1.9618e+00,  1.1899e-01,  7.0622e-04,  1.8619e+00,
          1.5509e+00, -1.5443e+00,  5.6568e-01],
        [ 1.9351e-01,  7.9869e-01,  1.3246e+00, -8.8030e-01, -2.4391e-01,
          5.3702e-01,  7.9829e-01,  7.0993e-01],
        [ 4.8424e-01, -5.5483e-01, -5.0217e-01,  6.8145e-01,  4.2363e-01,
         -1.4344e-01,  9.2017e-01, -1.5657e+00]])

In [ ]:
inputs.T

tensor([[ 6.3263e-01, -6.7296e-01,  1.9351e-01,  4.8424e-01],
        [ 5.5277e-01, -1.9618e+00,  7.9869e-01, -5.5483e-01],
        [-9.8654e-01,  1.1899e-01,  1.3246e+00, -5.0217e-01],
        [ 1.9623e+00,  7.0622e-04, -8.8030e-01,  6.8145e-01],
        [ 1.7586e-01,  1.8619e+00, -2.4391e-01,  4.2363e-01],
        [-3.2208e-01,  1.5509e+00,  5.3702e-01, -1.4344e-01],
        [-7.5031e-01, -1.5443e+00,  7.9829e-01,  9.2017e-01],
        [-1.5885e-02,  5.6568e-01,  7.0993e-01, -1.5657e+00]])

In [ ]:
# get all of the attention scores via a matrix multiplication:
attention_scores = inputs @ inputs.T
attention_scores

tensor([[ 6.2274, -0.6485, -3.2963,  1.2874],
        [-0.6485, 12.8923, -1.9926, -1.0371],
        [-3.2963, -1.9926,  4.6939, -2.1718],
        [ 1.2874, -1.0371, -2.1718,  4.7570]])

In [ ]:
attention_weights = torch.softmax( attention_scores, dim = -1 )
attention_weights

tensor([[9.9181e-01, 1.0239e-03, 7.2497e-05, 7.0960e-03],
        [1.3162e-06, 1.0000e+00, 3.4323e-07, 8.9240e-07],
        [3.3786e-04, 1.2443e-03, 9.9738e-01, 1.0402e-03],
        [3.0072e-02, 2.9420e-03, 9.4588e-04, 9.6604e-01]])

In [ ]:
attention_weights[0].sum()

tensor(1.0000)

In [ ]:
context_vectors = attention_weights @ inputs
context_vectors

tensor([[ 6.3021e-01,  5.4235e-01, -9.8180e-01,  1.9510e+00,  1.7931e-01,
         -3.1883e-01, -7.3916e-01, -2.6234e-02],
        [-6.7296e-01, -1.9618e+00,  1.1899e-01,  7.0911e-04,  1.8619e+00,
          1.5509e+00, -1.5443e+00,  5.6568e-01],
        [ 1.9288e-01,  7.9376e-01,  1.3204e+00, -8.7662e-01, -2.4046e-01,
          5.3728e-01,  7.9497e-01,  7.0714e-01],
        [ 4.8503e-01, -5.2438e-01, -5.1318e-01,  7.1649e-01,  4.1978e-01,
         -1.4318e-01,  8.6257e-01, -1.5107e+00]])